// AUTO-GENERATED by python -m tactiq.export_centroids — do not edit by hand.
// Source: sim1 (simulated data, 160 trials, generated 2026-07-19)
// PLACEHOLDER from SIMULATED data: regenerate from a real calibration before any user-facing build.
#pragma once

#define N_CLASSES 8
#define N_FEATURES 5

// feature order: flexDelta1, flexDelta2, fsrPeak1, fsrPeak2, peakAccelG
static const char* const CLASS_KEYS[N_CLASSES] = {
  "index_tip", "index_base", "middle_tip", "middle_base", "ring_tip", "ring_base", "pinky_tip", "pinky_base"
};
// brief-tap token per class (the 5 s emergency hold is decoded by duration)
static const char* const CLASS_TOKENS[N_CLASSES] = {
  "confirm", "back", "undo", "next", "read", "previous", "quick_action_1", "quick_action_2"
};
static const float CENTROID_MEAN[N_CLASSES][N_FEATURES] = {
  {190.500f, 418.400f, 1205.750f, 94.700f, 2.038f},
  {131.550f, 432.650f, 96.450f, 1067.400f, 1.984f},
  {287.200f, 329.450f, 1217.600f, 93.500f, 1.958f},
  {230.500f, 328.700f, 97.200f, 1040.850f, 1.857f},
  {395.850f, 231.100f, 1213.300f, 94.250f, 1.891f},
  {330.050f, 228.750f, 95.400f, 1042.750f, 1.838f},
  {477.900f, 129.300f, 1255.500f, 93.850f, 1.791f},
  {433.850f, 129.050f, 94.950f, 1043.350f, 1.692f},
};
static const float FEATURE_SCALE[N_FEATURES] = {
  116.938f, 112.975f, 568.991f, 479.833f, 0.163f
};
