"""Export a trained model's class centroids as a firmware header.

The on-device first pass (paper section 3.2: "threshold rules suffice for a
first pass") is a nearest-centroid classifier over the features the MCU can
compute in place; this script turns tactiq.classify's centroids.json into
firmware/tactiq_ring_ble/centroids.h.

Usage:
    python -m tactiq.export_centroids data/analysis/sim1 \
        -o ../firmware/tactiq_ring_ble/centroids.h
"""

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

from .contacts import KEYS
from .grammar import TAP_TOKENS

# what the MCU computes per press, in this exact order
ONBOARD_FEATURES = ["flexDelta1", "flexDelta2", "fsrPeak1", "fsrPeak2",
                    "peakAccelG"]


def render_header(centroids: dict, metrics: dict, source_dir: str) -> str:
    idx = [centroids["features"].index(f) for f in ONBOARD_FEATURES]
    lines = [
        "// AUTO-GENERATED by python -m tactiq.export_centroids — do not "
        "edit by hand.",
        f"// Source: {source_dir} ({metrics['source']} data, "
        f"{metrics['trials']} trials, generated "
        f"{dt.date.today().isoformat()})",
    ]
    if metrics["source"] == "simulated":
        lines.append("// PLACEHOLDER from SIMULATED data: regenerate from a "
                     "real calibration before any user-facing build.")
    lines += [
        "#pragma once", "",
        f"#define N_CLASSES {len(KEYS)}",
        f"#define N_FEATURES {len(ONBOARD_FEATURES)}", "",
        "// feature order: " + ", ".join(ONBOARD_FEATURES),
        "static const char* const CLASS_KEYS[N_CLASSES] = {",
        "  " + ", ".join(f'"{k}"' for k in KEYS), "};",
        "// brief-tap token per class (the 5 s emergency hold is decoded "
        "by duration)",
        "static const char* const CLASS_TOKENS[N_CLASSES] = {",
        "  " + ", ".join(f'"{TAP_TOKENS[k]}"' for k in KEYS), "};",
        "static const float CENTROID_MEAN[N_CLASSES][N_FEATURES] = {",
    ]
    for k in KEYS:
        vals = [centroids["means"][k][i] for i in idx]
        lines.append("  {" + ", ".join(f"{v:.3f}f" for v in vals) + "},")
    scale = [max(centroids["scale"][i], 1e-6) for i in idx]
    lines += [
        "};",
        "static const float FEATURE_SCALE[N_FEATURES] = {",
        "  " + ", ".join(f"{v:.3f}f" for v in scale), "};", "",
    ]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("analysis_dir", type=Path,
                    help="output dir of tactiq.classify or a "
                         "calibration_model dir")
    ap.add_argument("-o", "--out", type=Path, default=None,
                    help="default: <repo>/firmware/tactiq_ring_ble/"
                         "centroids.h")
    args = ap.parse_args(argv)

    centroids = json.loads((args.analysis_dir / "centroids.json").read_text())
    metrics = json.loads((args.analysis_dir / "metrics.json").read_text())
    out = args.out or (Path(__file__).resolve().parents[2] / "firmware" /
                       "tactiq_ring_ble" / "centroids.h")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_header(centroids, metrics, args.analysis_dir.name))
    print(f"Wrote {out} ({metrics['source']} data)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
